### ISSUE TITLE
Rollout template updates to existing repos

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/devops#10]

**Comment by nutjob4life** [comment]
I think this is much more than a size "1" task—not because it requires a clever mind, but _endurance_. We have 67 repositories—say 45 of those are actual code repositories. Even 30 would be a lot to go through, one-by-one, and convert from `setup.py`→`setup.cfg` or correlate `pom.xml` inheritance or even just update NOTICE and SECURITY files.

**Comment by jordanpadams** [comment]
@nutjob4life feel free to update the estimate. I was thinking it would take 1 work day to complete (~5-6 per hour), but you're probably right. Something will break and require some debugging (like when I tried to retrofit pds-deep-archive this AM and it broke and I had no idea why 😁

**Comment by nutjob4life** [comment]
Thanks @jordanpadams! Made it a 5 for now. We'll see how that feels. (I'm not much of a poker player 😝)

**Comment by jordanpadams** [comment]
@nutjob4life let's put a quick pause on this for a sec. looks like some of our repos out there do not really need to be retrofitted (e.g. some empty repo or no code has been committed yet). let's focus on the active repos, and we can retrofit the others when we get to them. this list may include repos we can't really retrofit for a specific codebase, but we can at least cleanup the READMEs.
- [ ] https://github.com/NASA-PDS/pds4-jparser
- [ ] https://github.com/NASA-PDS/pds-api-javalib
- [ ] https://github.com/NASA-PDS/registry-api-service
- [ ] https://github.com/NASA-PDS/pds-api-client
- [ ] https://github.com/NASA-PDS/pds-api
- [ ] https://github.com/NASA-PDS/nasa-pds.github.io
- [ ] https://github.com/NASA-PDS/pds4-information-model
- [ ] https://github.com/NASA-PDS/validate
- [ ] https://github.com/NASA-PDS/pds-deep-archive
- [ ] https://github.com/NASA-PDS/pdsen-corral
- [ ] https://github.com/NASA-PDS/pds-github-util
- [ ] https://github.com/NASA-PDS/pds-doi-service
- [ ] https://github.com/NASA-PDS/harvest
- [ ] https://github.com/NASA-PDS/pds-registry-app
- [ ] https://github.com/NASA-PDS/pds-api-notebook
- [ ] https://github.com/NASA-PDS/pdsen-operations (should be a python repo)
- [ ] https://github.com/NASA-PDS/api-search-query-lexer
- [ ] https://github.com/NASA-PDS/pds-registry-mgr-elastic
- [ ] https://github.com/NASA-PDS/pds-registry-common
- [ ] https://github.com/NASA-PDS/supplementer
- [ ] https://github.com/NASA-PDS/pdsen-maven-parent
- [ ] https://github.com/NASA-PDS/pds-view
- [ ] https://github.com/NASA-PDS/mi-label

**Comment by MJJoyce** [comment]
We might want to test the waters with the new Python template repo prior to pushing it out across all the existing repos. There's a non-trivial amount of changes that the new template might introduce (`black` is going to completely reformat existing code, flake8 linting errors, tox command changes, etc.) that might be good to test drive. I'm not suuuper familiar with the inner workings of `Roundup` but we'll also want it to work through the new test interfaces (especially since some of the old ones might not work).

Also, +1, not a 1. Not hard work but man will it be tedious and drawn out -_-

**Comment by jordanpadams** [comment]
@MJJoyce copy. another reason why I prioritizing repos would be useful. we can do this as we get to a repo that will be use by our community. in the above, only 2 are python repos. the rest are Java.

That being said, did we setup a linter for Java as well?
